// Generated by CoffeeScript 1.6.1
var burnparticle01,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

burnparticle01 = (function(_super) {

  __extends(burnparticle01, _super);

  function burnparticle01(initparam) {
    burnparticle01.__super__.constructor.call(this, initparam);
    this.damp = parseInt(rand(4) + 1.0) / 10.0;
  }

  burnparticle01.prototype.destructor = function() {
    return burnparticle01.__super__.destructor.call(this);
  };

  burnparticle01.prototype.behavior = function() {
    burnparticle01.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        this.opacity -= 0.1;
        this.scaleX *= 0.9;
        this.scaleY *= 0.9;
        this.xs *= this.damp;
        this.ys *= this.damp;
        if (this.opacity < 0) {
          return removeObject(this);
        }
    }
  };

  return burnparticle01;

})(_stationary);
