// Generated by CoffeeScript 1.6.1
var burnparticle02,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

burnparticle02 = (function(_super) {

  __extends(burnparticle02, _super);

  function burnparticle02(initparam) {
    burnparticle02.__super__.constructor.call(this, initparam);
  }

  burnparticle02.prototype.destructor = function() {
    return burnparticle02.__super__.destructor.call(this);
  };

  burnparticle02.prototype.behavior = function() {
    burnparticle02.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        this.opacity -= 0.05;
        this.scaleX *= 0.9;
        this.scaleY *= 0.9;
        if (this.opacity < 0) {
          return removeObject(this);
        }
    }
  };

  return burnparticle02;

})(_stationary);
