// Generated by CoffeeScript 1.6.1
var enemyBullet,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

enemyBullet = (function(_super) {

  __extends(enemyBullet, _super);

  function enemyBullet(initparam) {
    var collider;
    enemyBullet.__super__.constructor.call(this, initparam);
    this.gamecontrolobj = GLOBAL['gamecontrol'];
    this.stagecontrolobj = GLOBAL['stagecontrol'];
    this.worldend = GLOBAL['worldend'];
    collider = addObject({
      type: COLLIDER2D,
      image: 'collider',
      width: 8,
      height: 8,
      x: this.x,
      y: this.y
    });
    this.collider = collider;
  }

  enemyBullet.prototype.destructor = function() {
    return enemyBullet.__super__.destructor.call(this);
  };

  enemyBullet.prototype.behavior = function() {
    enemyBullet.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        if (this.x < -this.width || this.worldend.x + this.width < this.x || -this.height > this.y || this.y > this.worldend.y + this.height) {
          return this.stagecontrolobj.enemyRemoveBullet(this);
        }
    }
  };

  return enemyBullet;

})(_stationary);
