// Generated by CoffeeScript 1.6.1
var enforceMain;

enforceMain = (function() {

  function enforceMain() {
    var gameControlObj;
    gameControlObj = addObject({
      type: CONTROL,
      motionObj: gameControl
    });
  }

  return enforceMain;

})();
