// Generated by CoffeeScript 1.6.1
var myshipBullet,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

myshipBullet = (function(_super) {

  __extends(myshipBullet, _super);

  function myshipBullet(initparam) {
    myshipBullet.__super__.constructor.call(this, initparam);
    this.gamecontrolobj = GLOBAL['gamecontrol'];
    this.stagecontrolobj = GLOBAL['stagecontrol'];
    this.ys = -20;
  }

  myshipBullet.prototype.destructor = function() {
    return myshipBullet.__super__.destructor.call(this);
  };

  myshipBullet.prototype.behavior = function() {
    myshipBullet.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        if (this.y < -this.height) {
          return this.stagecontrolobj.myshipRemoveBullet(this);
        }
    }
  };

  return myshipBullet;

})(_stationary);
