// Generated by CoffeeScript 1.6.1
var startbutton,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

startbutton = (function(_super) {

  __extends(startbutton, _super);

  function startbutton(initparam) {
    startbutton.__super__.constructor.call(this, initparam);
  }

  startbutton.prototype.destructor = function() {
    return startbutton.__super__.destructor.call(this);
  };

  startbutton.prototype.behavior = function() {
    startbutton.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        return nop();
    }
  };

  startbutton.prototype.touchesBegan = function(pos) {
    startbutton.__super__.touchesBegan.call(this, pos);
    this.x += 2;
    return this.y += 2;
  };

  startbutton.prototype.touchesEnded = function(pos) {
    startbutton.__super__.touchesEnded.call(this, pos);
    this.x -= 2;
    this.y -= 2;
    if (this.x - (this.width / 2) < pos.x && this.y - (this.height / 2) < pos.y && pos.x < this.x + (this.width / 2) && pos.y < this.y + (this.height / 2)) {
      if (this.parent._processnumber === 2) {
        playSound('gamestart');
        return this.parent.waitjob(1);
      }
    }
  };

  return startbutton;

})(_stationary);
