// Generated by CoffeeScript 1.6.1
var topscene,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

topscene = (function(_super) {

  __extends(topscene, _super);

  function topscene(initparam) {
    topscene.__super__.constructor.call(this, initparam);
  }

  topscene.prototype.destructor = function() {
    return topscene.__super__.destructor.call(this);
  };

  topscene.prototype.behavior = function() {
    topscene.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        return nop();
    }
  };

  return topscene;

})(_stationary);
